name: Build DynamicArray.a

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get -y install clang lld

    - name: Clean library
      run:  cd lib_dynamic_linked_array && make clean
      
    - name: Build library
      run: cd lib_dynamic_linked_array && make lib