name: C Lint

on:
  push:
    branches:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get -y install clang lld

    - name: Make library
      run: cd mylib && make lib
